services:
  # --- DOWNLOAD ENGINE ---
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./Media/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # --- REMOTE ACCESS ---
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: jellyfin-server
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  # --- MEDIA AUTOMATION ---
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ./radarr/config:/config
      - ./Media/Movies:/movies
      - ./Media/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./sonarr/config:/config
      - ./Media/TVShows:/tv
      - ./Media/Downloads:/downloads
      - ./Media/Anime:/anime  
      - ./Media/WebSeries:/series
    environment:
      - PUID=1000
      - PGID=1000

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ./bazarr/config:/config
      - ./Media/TVShows:/tv
      - ./Media/Downloads:/downloads
      - ./Media/Anime:/anime  
      - ./Media/WebSeries:/series
      - ./Media/Movies:/movies
    environment:
      - PUID=1000
      - PGID=1000

  # --- MEDIA SERVER ---
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped 
    ports:
      - "8096:8096"
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./Media:/media
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=http://localhost:8096
    group_add:
      - "105"   # render group